### ISSUE TITLE
getting error as shown below

### ISSUE THREAD

**Issue by vbpatel73** [PauloGoncalvesBH/running-playwright-on-aws-lambda#4]
error: 'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1',

**Comment by PauloGoncalvesBH** [comment]
Hello @vbpatel73, I created a documentation about how to deploy and run the tests at AWS Lambda: https://github.com/PauloGoncalvesBH/running-playwright-on-aws-lambda#deploying-at-aws-lambda

If the error stills, please open a new issue.
